package org.openstack.atlas.service.domain.events.entities;

import java.io.Serializable;

public enum EventType implements Serializable {
    BUILD_LOADBALANCER,
    CREATE_LOADBALANCER,
    PENDING_UPDATE_LOADBALANCER,
    UPDATE_LOADBALANCER,
    PENDING_DELETE_LOADBALANCER,
    DELETE_LOADBALANCER,
    CREATE_NODE,
    UPDATE_NODE,
    DELETE_NODE,
    CREATE_VIRTUAL_IP,
    DELETE_VIRTUAL_IP,
    DELETE_NETWORK_ITEM,
    CREATE_ACCESS_LIST,
    UPDATE_ACCESS_LIST,
    DELETE_ACCESS_LIST,
    CREATE_CONNECTION_THROTTLE,
    UPDATE_CONNECTION_THROTTLE,
    DELETE_CONNECTION_THROTTLE,
    CREATE_HEALTH_MONITOR,
    UPDATE_HEALTH_MONITOR,
    DELETE_HEALTH_MONITOR,
    CREATE_SESSION_PERSISTENCE,
    UPDATE_SESSION_PERSISTENCE,
    DELETE_SESSION_PERSISTENCE,
    UPDATE_CONNECTION_LOGGING,
    UPDATE_CONTENT_CACHING,
    UPDATE_SSL_TERMINATION,
    DELETE_SSL_TERMINATION,
    AH_USAGE_EXECUTION;

    private final static long serialVersionUID = 532512316L;
}