use `loadbalancing`;

set FOREIGN_KEY_CHECKS = 0;

drop table `access_list`;
drop table `access_list_type`;
drop table `cluster`;
drop table `connection_limit`;
drop table `health_monitor`;
drop table `health_monitor_type`;
drop table `host`;
drop table `host_backup`;
drop table `host_status`;
drop table `lb_algorithm`;
drop table `lb_data_center`;
drop table `lb_protocol`;
drop table `lb_rate_limit`;
drop table `lb_session_persistence`;
drop table `lb_status`;
drop table `lb_suspension`;
drop table `lb_usage`;
drop table `account_usage`;
drop table `lb_zone`;
drop table `loadbalancer`;
drop table `loadbalancer_virtualip`;
drop table `node`;
drop table `node_condition`;
drop table `node_status`;
drop table `virtual_ip`;
drop table `virtual_ip_type`;
drop table `allocated_virtual_ip`;
drop table `meta`;
drop table `traffic_scripts`;
