#!/usr/bin/env python

import socket
import ssl
import sys
import os


def printf(format,*args): sys.stdout.write(format%args)

def usage(prog):
    printf("usage is %s <host> <port>\n", prog)
    printf("\n")
    printf("do a simple http connect\n")

if __name__ == "__main__":
    prog = os.path.basename(sys.argv[0])
    if len(sys.argv)<3:
        usage(prog)
        sys.exit()
    host = sys.argv[1]
    port = int(sys.argv[2])

    s = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
    s.connect((host,port))
    sw = ssl.wrap_socket(s,cert_reqs=ssl.CERT_NONE)
    sw.send("GET / HTTP/1.1\r\nHost: %s\r\n\r\n"%host)
    printf("Request sent\nReading data")
    sys.stdout.flush()
    while True:
        data = sw.recv(1024)
        if len(data)<=0:
            break
        printf("%s",data)
        sys.stdout.flush()
    printf("\nno more data read\n")
    sw.close()
