//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.31 at 01:53:34 AM CDT 
//


package com.rackspace.docs.event.lbaas.delete;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rackspace.docs.event.lbaas.delete package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Product_QNAME = new QName("http://docs.rackspace.com/event/lbaas/delete", "product");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rackspace.docs.event.lbaas.delete
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CloudLoadBalancersType }
     * 
     */
    public CloudLoadBalancersType createCloudLoadBalancersType() {
        return new CloudLoadBalancersType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloudLoadBalancersType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CloudLoadBalancersType }{@code >}
     */
    @XmlElementDecl(namespace = "http://docs.rackspace.com/event/lbaas/delete", name = "product")
    public JAXBElement<CloudLoadBalancersType> createProduct(CloudLoadBalancersType value) {
        return new JAXBElement<CloudLoadBalancersType>(_Product_QNAME, CloudLoadBalancersType.class, null, value);
    }

}
