//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.31 at 01:53:34 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://docs.rackspace.com/event/lbaas/delete")
package com.rackspace.docs.event.lbaas.delete;
