package org.openstack.atlas.api.atom;

public enum FeedType {
    PARENT_FEED,
    LOADBALANCER_FEED,
    NODES_FEED,
    NODE_SERVICE_FEED,
    NODE_FEED,
    VIRTUAL_IPS_FEED,
    ACCESS_LIST_FEED,
    CONNECTION_THROTTLE_FEED,
    HEALTH_MONITOR_FEED,
    SESSION_PERSISTENCE_FEED;
}
