//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.31 at 01:53:34 AM CDT 
//


package com.rackspace.docs.core.event;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;html:p xmlns:html="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:event="http://docs.rackspace.com/core/event" xmlns:saxon="http://saxon.sf.net/" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:xerces="http://xerces.apache.org" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
 *                     Event information version 1.
 *                 &lt;/html:p&gt;
 * </pre>
 * 
 *             
 * 
 * <p>Java class for EventV1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventV1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://docs.rackspace.com/core/event}EventBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="tenantId" type="{http://docs.rackspace.com/core/event}NonEmptyString" /&gt;
 *       &lt;attribute name="resourceId" type="{http://docs.rackspace.com/core/event}NonEmptyString" /&gt;
 *       &lt;attribute name="id" use="required" type="{http://docs.rackspace.com/core/event}UUID" /&gt;
 *       &lt;attribute name="referenceId" type="{http://docs.rackspace.com/core/event}UUID" /&gt;
 *       &lt;attribute name="rootAction" type="{http://docs.rackspace.com/core/event}NonEmptyString" /&gt;
 *       &lt;attribute name="type" use="required" type="{http://docs.rackspace.com/core/event}EventType" /&gt;
 *       &lt;attribute name="environment" type="{http://docs.rackspace.com/core/event}ENVIRONMENT" default="PROD" /&gt;
 *       &lt;attribute name="dataCenter" type="{http://docs.rackspace.com/core/event}DC" default="GLOBAL" /&gt;
 *       &lt;attribute name="region" type="{http://docs.rackspace.com/core/event}Region" default="GLOBAL" /&gt;
 *       &lt;attribute name="startTime" type="{http://docs.rackspace.com/core/event}UTCDateTime" /&gt;
 *       &lt;attribute name="endTime" type="{http://docs.rackspace.com/core/event}UTCDateTime" /&gt;
 *       &lt;attribute name="eventTime" type="{http://docs.rackspace.com/core/event}UTCDateTime" /&gt;
 *       &lt;attribute name="resourceName" type="{http://docs.rackspace.com/core/event}NonEmptyString" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventV1", propOrder = {
    "any"
})
@XmlSeeAlso({
    V1Element.class
})
public class EventV1
    extends EventBase
{

    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "tenantId")
    protected String tenantId;
    @XmlAttribute(name = "resourceId")
    protected String resourceId;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "referenceId")
    protected String referenceId;
    @XmlAttribute(name = "rootAction")
    protected String rootAction;
    @XmlAttribute(name = "type", required = true)
    protected EventType type;
    @XmlAttribute(name = "environment")
    protected ENVIRONMENT environment;
    @XmlAttribute(name = "dataCenter")
    protected DC dataCenter;
    @XmlAttribute(name = "region")
    protected Region region;
    @XmlAttribute(name = "startTime")
    protected XMLGregorianCalendar startTime;
    @XmlAttribute(name = "endTime")
    protected XMLGregorianCalendar endTime;
    @XmlAttribute(name = "eventTime")
    protected XMLGregorianCalendar eventTime;
    @XmlAttribute(name = "resourceName")
    protected String resourceName;

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the tenantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * Sets the value of the tenantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenantId(String value) {
        this.tenantId = value;
    }

    /**
     * Gets the value of the resourceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * Sets the value of the resourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceId(String value) {
        this.resourceId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the referenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * Sets the value of the referenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceId(String value) {
        this.referenceId = value;
    }

    /**
     * Gets the value of the rootAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootAction() {
        return rootAction;
    }

    /**
     * Sets the value of the rootAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootAction(String value) {
        this.rootAction = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EventType }
     *     
     */
    public EventType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventType }
     *     
     */
    public void setType(EventType value) {
        this.type = value;
    }

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link ENVIRONMENT }
     *     
     */
    public ENVIRONMENT getEnvironment() {
        if (environment == null) {
            return ENVIRONMENT.PROD;
        } else {
            return environment;
        }
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ENVIRONMENT }
     *     
     */
    public void setEnvironment(ENVIRONMENT value) {
        this.environment = value;
    }

    /**
     * Gets the value of the dataCenter property.
     * 
     * @return
     *     possible object is
     *     {@link DC }
     *     
     */
    public DC getDataCenter() {
        if (dataCenter == null) {
            return DC.GLOBAL;
        } else {
            return dataCenter;
        }
    }

    /**
     * Sets the value of the dataCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link DC }
     *     
     */
    public void setDataCenter(DC value) {
        this.dataCenter = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link Region }
     *     
     */
    public Region getRegion() {
        if (region == null) {
            return Region.GLOBAL;
        } else {
            return region;
        }
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link Region }
     *     
     */
    public void setRegion(Region value) {
        this.region = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTime(XMLGregorianCalendar value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the eventTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventTime() {
        return eventTime;
    }

    /**
     * Sets the value of the eventTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventTime(XMLGregorianCalendar value) {
        this.eventTime = value;
    }

    /**
     * Gets the value of the resourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * Sets the value of the resourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceName(String value) {
        this.resourceName = value;
    }

}
