//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.31 at 01:53:34 AM CDT 
//


package com.rackspace.docs.core.event;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Region.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Region"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="GLOBAL"/&gt;
 *     &lt;enumeration value="DFW"/&gt;
 *     &lt;enumeration value="HKG"/&gt;
 *     &lt;enumeration value="IAD"/&gt;
 *     &lt;enumeration value="LON"/&gt;
 *     &lt;enumeration value="ORD"/&gt;
 *     &lt;enumeration value="SYD"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Region")
@XmlEnum
public enum Region {

    GLOBAL,
    DFW,
    HKG,
    IAD,
    LON,
    ORD,
    SYD;

    public String value() {
        return name();
    }

    public static Region fromValue(String v) {
        return valueOf(v);
    }

}
