//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.31 at 01:53:34 AM CDT 
//


package org.w3._2005.atom;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2005.atom package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Entry_QNAME = new QName("http://www.w3.org/2005/Atom", "entry");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2005.atom
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UsageEntry }
     * 
     */
    public UsageEntry createUsageEntry() {
        return new UsageEntry();
    }

    /**
     * Create an instance of {@link LooseContent }
     * 
     */
    public LooseContent createLooseContent() {
        return new LooseContent();
    }

    /**
     * Create an instance of {@link UsageContent }
     * 
     */
    public UsageContent createUsageContent() {
        return new UsageContent();
    }

    /**
     * Create an instance of {@link UsageCategory }
     * 
     */
    public UsageCategory createUsageCategory() {
        return new UsageCategory();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsageEntry }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UsageEntry }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "entry")
    public JAXBElement<UsageEntry> createEntry(UsageEntry value) {
        return new JAXBElement<UsageEntry>(_Entry_QNAME, UsageEntry.class, null, value);
    }

}
