//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.06 at 11:19:15 PM CST 
//

// org.openstack.atlas.service.domain.events.pojos.LoadBalancerServiceEvents
package org.openstack.atlas.service.domain.events.pojos;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import org.openstack.atlas.service.domain.events.entities.LoadBalancerServiceEvent;

public class LoadBalancerServiceEvents
    implements Serializable
{

    private final static long serialVersionUID = 532512316L;
    protected List<LoadBalancerServiceEvent> loadBalancerServiceEvents;
    protected Integer loadbalancerId;
    public List<LoadBalancerServiceEvent> getLoadBalancerServiceEvents() {
        if (loadBalancerServiceEvents == null) {
            loadBalancerServiceEvents = new ArrayList<LoadBalancerServiceEvent>();
        }
        return this.loadBalancerServiceEvents;
    }

    public Integer getLoadbalancerId() {
        return loadbalancerId;
    }

    public void setLoadbalancerId(Integer value) {
        this.loadbalancerId = value;
    }

}
