//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.06 at 11:19:15 PM CST 
//

// org.openstack.atlas.service.domain.events.pojos.LoadBalancerServiceEvents
package org.openstack.atlas.service.domain.events.pojos;

import org.openstack.atlas.service.domain.events.entities.NodeServiceEvent;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class NodeServiceEvents
    implements Serializable
{

    private final static long serialVersionUID = 532512316L;
    protected List<NodeServiceEvent> nodeServiceEvents;
    protected Integer loadbalancerId;
    protected Integer nodeId;
    public List<NodeServiceEvent> getNodeServiceEvents() {
        if (nodeServiceEvents == null) {
            nodeServiceEvents = new ArrayList<NodeServiceEvent>();
        }
        return this.nodeServiceEvents;
    }

    public Integer getLoadbalancerId() {
        return loadbalancerId;
    }

    public void setLoadbalancerId(Integer value) {
        this.loadbalancerId = value;
    }

    public Integer getNodeId() {
        return nodeId;
    }

    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }
}
