#!/usr/bin/env python

import cfuploader.app
import cfuploader.utils
import os

log = cfuploader.utils.log

if __name__ == "__main__":
    pid = os.getpid()
    log("pid = %i\n", pid)
    uploader = cfuploader.app.Uploader()
    uploader.main_loop()