#!/usr/bin/env python

import sys
import os


def printf(format,*args): sys.stdout.write(format%args)

def usage(prog):
    printf("Usage is %s <file_path>\n",prog)
    printf("\n")
    printf("Print the absolute path to the file_path\n")

prog = os.path.basename(sys.argv[0])

if len(sys.argv)<2:
    usage(prog)
    sys.exit()

file_path = os.path.expanduser(sys.argv[1])
printf("%s\n",os.path.abspath(file_path))

